app/urls.py
from django.urls import path
from app.views import *

app_name='virat'

urlpatterns=[
    path('virat/',virat,name='virat'),
]

app2/urls.py
from django.urls import path
from app2.views import*

app_name='dhoni'

urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

project5/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app2 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def virat(request):
    return render(request,'virat.html')
    

app2/views.py
from django.shortcuts import render

# Create your views here.

def dhoni(request):
    return render(request,'dhoni.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1:hover{
            color: rgb(111, 224, 70);
            background-color:rgb(118, 45, 116);
        }
        a:hover{
            background-color: rgb(97, 156, 137);
        }
    </style>
</head>
<body>
    <center>
        <h1>This is Dhoni Html page</h1>
        <h1>Welcome To Dhoni Page</h1>
        <a href="{% url 'virat:virat' %}">Navigate To Dhoni Page</a>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            background-color: aqua;
            color: red;
        }
        a{
            color:rgb(55, 174, 99);
        }
    </style>
</head>
<body>
    <center>
        <h1>This Is Virat html Page</h1>
        <h1>Welcome To Virat Page</h1>
        <a  href="{% url 'dhoni:dhoni' %}">Navigate TO Virat Page</a>
    </center>
</body>
</html>